// Generated 10 Nov 2021 11:59 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.OrderDetails
{
    [Serializable]
    public class OrderDetailList
     : SingularBusinessListBase<OrderDetailList, OrderDetail>
    {
        #region " Business Methods "

        public OrderDetail GetItem(int OrderDetailsID)
        {
            foreach (OrderDetail child in this)
            {
                if (child.OrderDetailsID == OrderDetailsID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Order Details";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }
            public int UserID { get; set; }
            public int OrderID { get; set; }

        }

        public static OrderDetailList NewOrderDetailList()
        {
            return new OrderDetailList();
        }

        public OrderDetailList()
        {
            // must have parameter-less constructor
        }

        public static OrderDetailList GetOrderDetailList()
        {
            return DataPortal.Fetch<OrderDetailList>(new Criteria());
        }

        public static OrderDetailList GetOrderDetailListID(int OrderID,int UserID)
        {
            return DataPortal.Fetch<OrderDetailList>(new Criteria() { OrderID = OrderID, UserID=UserID});
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(OrderDetail.GetOrderDetail(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getOrderDetailList";
                        cm.Parameters.AddWithValue("@UserID", Singular.Security.Security.CurrentIdentity.UserID);
                        cm.Parameters.AddWithValue("@OrderID",Misc.NothingDBNull(crit.OrderID));


                        //cm.Parameters.AddWithValue("@ForgotEmail", Misc.NothingDBNull(crit.ForgotEmail));

                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}