// Generated 17 Nov 2021 14:35 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Promotions
{
    [Serializable]
    public class SnackPromoList
     : SingularBusinessListBase<SnackPromoList, SnackPromo>
    {
        #region " Business Methods "

        public SnackPromo GetItem(int SnackID)
        {
            foreach (SnackPromo child in this)
            {
                if (child.SnackID == SnackID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Snacks";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

            public DateTime ReleaseDate { get; set; }

        }

        public static SnackPromoList NewSnackPromoList()
        {
            return new SnackPromoList();
        }

        public SnackPromoList()
        {
            // must have parameter-less constructor
        }

        public static SnackPromoList GetSnackPromoList()
        {
            return DataPortal.Fetch<SnackPromoList>(new Criteria() );
        }

        public static SnackPromoList GetSnackPromoListID(DateTime ReleaseDate)
        {
            return DataPortal.Fetch<SnackPromoList>(new Criteria() { ReleaseDate = ReleaseDate });
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(SnackPromo.GetSnackPromo(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getSnackPromo";

                       // cm.Parameters.AddWithValue("@ReleaseDate", Misc.NothingDBNull(crit.ReleaseDate));

                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}