// Generated 22 Oct 2021 09:10 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.TvShows
{
    [Serializable]
    public class TvShowList
     : SingularBusinessListBase<TvShowList, TvShow>
    {
        #region " Business Methods "

        public TvShow GetItem(int TvShowID)
        {
            foreach (TvShow child in this)
            {
                if (child.TvShowID == TvShowID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Tv Shows";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static TvShowList NewTvShowList()
        {
            return new TvShowList();
        }

        public TvShowList()
        {
            // must have parameter-less constructor
        }

        public static TvShowList GetTvShowList()
        {
            return DataPortal.Fetch<TvShowList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(TvShow.GetTvShow(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getTvShowList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}