// Generated 25 Oct 2021 09:32 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.SportShows
{
    [Serializable]
    public class SportShowList
     : SingularBusinessListBase<SportShowList, SportShow>
    {
        #region " Business Methods "

        public SportShow GetItem(int SportShowID)
        {
            foreach (SportShow child in this)
            {
                if (child.SportShowID == SportShowID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Sport Shows";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static SportShowList NewSportShowList()
        {
            return new SportShowList();
        }

        public SportShowList()
        {
            // must have parameter-less constructor
        }

        public static SportShowList GetSportShowList()
        {
            return DataPortal.Fetch<SportShowList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(SportShow.GetSportShow(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getSportShowList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}