// Generated 03 Jan 2021 10:59 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.RO
{
  [Serializable]
  public class ROSnackTypeList
   : MEReadOnlyListBase<ROSnackTypeList, ROSnackType>
  {
    #region " Business Methods "

    public ROSnackType GetItem(int SnackTypeID)
    {
      foreach (ROSnackType child in this)
      {
        if (child.SnackTypeID == SnackTypeID)
        {
          return child;
        }
      }
      return null;
    }

    public override string ToString()
    {
      return "Movie Genres";
    }

    #endregion

    #region " Data Access "

    [Serializable]
    public class Criteria
      : CriteriaBase<Criteria>
    {
      public Criteria()
      {
      }

    }

    public static ROSnackTypeList NewROSnackTypeList()
    {
      return new ROSnackTypeList();
    }

    public ROSnackTypeList()
    {
      // must have parameter-less constructor
    }

    public static ROSnackTypeList GetROSnackTypeList()
    {
      return DataPortal.Fetch<ROSnackTypeList>(new Criteria());
    }

    protected void Fetch(SafeDataReader sdr)
    {
      this.RaiseListChangedEvents = false;
      this.IsReadOnly = false;
      while (sdr.Read())
      {
        this.Add(ROSnackType.GetROSnackType(sdr));
      }
      this.IsReadOnly = true;
      this.RaiseListChangedEvents = true;
    }

    protected override void DataPortal_Fetch(Object criteria)
    {
      Criteria crit = (Criteria)criteria;
      using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
      {
        cn.Open();
        try
        {
          using (SqlCommand cm = cn.CreateCommand())
          {
            cm.CommandType = CommandType.StoredProcedure;
            cm.CommandText = "GetProcs.getROSnackTypeList";
            using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
            {
              Fetch(sdr);
            }
          }
        }
        finally
        {
          cn.Close();
        }
      }
    }

    #endregion

  }

}