// Generated 22 Oct 2021 16:08 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.KidsShows
{
    [Serializable]
    public class KidsShow
     : SingularBusinessBase<KidsShow>
    {
        #region " Properties and Methods "

        #region " Properties "

        public static PropertyInfo<int> KidIDProperty = RegisterProperty<int>(c => c.KidID, "ID", 0);
        /// <summary>
        /// Gets the ID value
        /// </summary>
        [Display(AutoGenerateField = false), Key]
        public int KidID
        {
            get { return GetProperty(KidIDProperty); }
        }

        public static PropertyInfo<int> MovieGenreIDProperty = RegisterProperty<int>(c => c.MovieGenreID, "Movie Genre", 0);
        /// <summary>
        /// Gets and sets the Movie Genre value
        /// </summary>
        [Display(Name = "Movie Genre", Description = ""),
        Required(ErrorMessage = "Movie Genre required")]
        public int MovieGenreID
        {
            get { return GetProperty(MovieGenreIDProperty); }
            set { SetProperty(MovieGenreIDProperty, value); }
        }

        public static PropertyInfo<String> KidTitleProperty = RegisterProperty<String>(c => c.KidTitle, "Kid Title", "");
        /// <summary>
        /// Gets and sets the Kid Title value
        /// </summary>
        [Display(Name = "Kid Title", Description = "Title of the Kid"),
        StringLength(200, ErrorMessage = "Kid Title cannot be more than 200 characters")]
        public String KidTitle
        {
            get { return GetProperty(KidTitleProperty); }
            set { SetProperty(KidTitleProperty, value); }
        }

        public static PropertyInfo<String> KidDescriptionProperty = RegisterProperty<String>(c => c.KidDescription, "Kid Description", "");
        /// <summary>
        /// Gets and sets the Kid Description value
        /// </summary>
        [Display(Name = "Kid Description", Description = "Short Description of the Kid")]
        public String KidDescription
        {
            get { return GetProperty(KidDescriptionProperty); }
            set { SetProperty(KidDescriptionProperty, value); }
        }

        public static PropertyInfo<String> KidImageURLProperty = RegisterProperty<String>(c => c.KidImageURL, "Kid Image URL", "../Media/Kids/blank.jpg");
        /// <summary>
        /// Gets and sets the Kid Image URL value
        /// </summary>
        [Display(Name = "Kid Image URL", Description = "")]
        public String KidImageURL
        {
            get { return GetProperty(KidImageURLProperty); }
            set { SetProperty(KidImageURLProperty, value); }
        }

        public static PropertyInfo<Decimal> PriceProperty = RegisterProperty<Decimal>(c => c.Price, "Price", Convert.ToDecimal(50));
        /// <summary>
        /// Gets and sets the Price value
        /// </summary>
        [Display(Name = "Price", Description = ""),
        Required(ErrorMessage = "Price required")]
        public Decimal Price
        {
            get { return GetProperty(PriceProperty); }
            set { SetProperty(PriceProperty, value); }
        }

        public static PropertyInfo<DateTime> ReleaseDateProperty = RegisterProperty<DateTime>(c => c.ReleaseDate, "Release Date");
        /// <summary>
        /// Gets and sets the Release Date value
        /// </summary>
        [Display(Name = "Release Date", Description = "Date of Release"),
        Required(ErrorMessage = "Release Date required")]
        public DateTime ReleaseDate
        {
            get
            {
                return GetProperty(ReleaseDateProperty);
            }
            set
            {
                SetProperty(ReleaseDateProperty, value);
            }
        }

        public static PropertyInfo<Boolean> IsActiveIndProperty = RegisterProperty<Boolean>(c => c.IsActiveInd, "Is Active", true);
        /// <summary>
        /// Gets and sets the Is Active value
        /// </summary>
        [Display(Name = "Is Active", Description = "Indicator showing if the Kid is Active"),
        Required(ErrorMessage = "Is Active required")]
        public Boolean IsActiveInd
        {
            get { return GetProperty(IsActiveIndProperty); }
            set { SetProperty(IsActiveIndProperty, value); }
        }

        public static PropertyInfo<DateTime?> DeletedDateProperty = RegisterProperty<DateTime?>(c => c.DeletedDate, "Deleted Date");
        /// <summary>
        /// Gets and sets the Deleted Date value
        /// </summary>
        [Display(Name = "Deleted Date", Description = "When this record was deleted")]
        public DateTime? DeletedDate
        {
            get
            {
                return GetProperty(DeletedDateProperty);
            }
            set
            {
                SetProperty(DeletedDateProperty, value);
            }
        }

        public static PropertyInfo<int> DeletedByProperty = RegisterProperty<int>(c => c.DeletedBy, "Deleted By", 0);
        /// <summary>
        /// Gets and sets the Deleted By value
        /// </summary>
        [Display(Name = "Deleted By", Description = "User that deleted the record")]
        public int DeletedBy
        {
            get { return GetProperty(DeletedByProperty); }
            set { SetProperty(DeletedByProperty, value); }
        }

        public static PropertyInfo<SmartDate> CreatedDateProperty = RegisterProperty<SmartDate>(c => c.CreatedDate, "Created Date", new SmartDate(DateTime.Now));
        /// <summary>
        /// Gets the Created Date value
        /// </summary>
        [Display(AutoGenerateField = false)]
        public SmartDate CreatedDate
        {
            get { return GetProperty(CreatedDateProperty); }
        }

        public static PropertyInfo<int> CreatedByProperty = RegisterProperty<int>(c => c.CreatedBy, "Created By", 0);
        /// <summary>
        /// Gets the Created By value
        /// </summary>
        [Display(AutoGenerateField = false)]
        public int CreatedBy
        {
            get { return GetProperty(CreatedByProperty); }
        }

        public static PropertyInfo<SmartDate> ModifiedDateProperty = RegisterProperty<SmartDate>(c => c.ModifiedDate, "Modified Date", new SmartDate(DateTime.Now));
        /// <summary>
        /// Gets the Modified Date value
        /// </summary>
        [Display(AutoGenerateField = false)]
        public SmartDate ModifiedDate
        {
            get { return GetProperty(ModifiedDateProperty); }
        }

        public static PropertyInfo<int> ModifiedByProperty = RegisterProperty<int>(c => c.ModifiedBy, "Modified By", 0);
        /// <summary>
        /// Gets the Modified By value
        /// </summary>
        [Display(AutoGenerateField = false)]
        public int ModifiedBy
        {
            get { return GetProperty(ModifiedByProperty); }
        }

        #endregion

        #region " Methods "

        protected override object GetIdValue()
        {
            return GetProperty(KidIDProperty);
        }

        public override string ToString()
        {
            if (this.KidTitle.Length == 0)
            {
                if (this.IsNew)
                {
                    return String.Format("New {0}", "Kids Show");
                }
                else
                {
                    return String.Format("Blank {0}", "Kids Show");
                }
            }
            else
            {
                return this.KidTitle;
            }
        }

        #endregion

        #endregion

        #region " Validation Rules "

        protected override void AddBusinessRules()
        {
            base.AddBusinessRules();
        }

        #endregion

        #region " Data Access & Factory Methods "

        protected override void OnCreate()
        {
            // This is called when a new object is created
            // Set any variables here, not in the constructor or NewKidsShow() method.
        }

        public static KidsShow NewKidsShow()
        {
            return DataPortal.CreateChild<KidsShow>();
        }

        public KidsShow()
        {
            MarkAsChild();
        }

        internal static KidsShow GetKidsShow(SafeDataReader dr)
        {
            var k = new KidsShow();
            k.Fetch(dr);
            return k;
        }

        protected void Fetch(SafeDataReader sdr)
        {
            using (BypassPropertyChecks)
            {
                int i = 0;
                LoadProperty(KidIDProperty, sdr.GetInt32(i++));
                LoadProperty(MovieGenreIDProperty, sdr.GetInt32(i++));
                LoadProperty(KidTitleProperty, sdr.GetString(i++));
                LoadProperty(KidDescriptionProperty, sdr.GetString(i++));
                LoadProperty(KidImageURLProperty, sdr.GetString(i++));
                LoadProperty(PriceProperty, sdr.GetDecimal(i++));
                LoadProperty(ReleaseDateProperty, sdr.GetValue(i++));
                LoadProperty(IsActiveIndProperty, sdr.GetBoolean(i++));
                LoadProperty(DeletedDateProperty, sdr.GetValue(i++));
                LoadProperty(DeletedByProperty, sdr.GetInt32(i++));
                LoadProperty(CreatedDateProperty, sdr.GetSmartDate(i++));
                LoadProperty(CreatedByProperty, sdr.GetInt32(i++));
                LoadProperty(ModifiedDateProperty, sdr.GetSmartDate(i++));
                LoadProperty(ModifiedByProperty, sdr.GetInt32(i++));
            }

            MarkAsChild();
            MarkOld();
            BusinessRules.CheckRules();
        }

        protected override Action<SqlCommand> SetupSaveCommand(SqlCommand cm)
        {
            LoadProperty(ModifiedByProperty, Settings.CurrentUser.UserID);

            AddPrimaryKeyParam(cm, KidIDProperty);

            cm.Parameters.AddWithValue("@MovieGenreID", GetProperty(MovieGenreIDProperty));
            cm.Parameters.AddWithValue("@KidTitle", GetProperty(KidTitleProperty));
            cm.Parameters.AddWithValue("@KidDescription", GetProperty(KidDescriptionProperty));
            cm.Parameters.AddWithValue("@KidImageURL", GetProperty(KidImageURLProperty));
            cm.Parameters.AddWithValue("@Price", GetProperty(PriceProperty));
            cm.Parameters.AddWithValue("@ReleaseDate", ReleaseDate);
            cm.Parameters.AddWithValue("@IsActiveInd", GetProperty(IsActiveIndProperty));
            cm.Parameters.AddWithValue("@DeletedDate", Singular.Misc.NothingDBNull(DeletedDate));
            cm.Parameters.AddWithValue("@DeletedBy", GetProperty(DeletedByProperty));
            cm.Parameters.AddWithValue("@ModifiedBy", GetProperty(ModifiedByProperty));

            return (scm) =>
            {
    // Post Save
    if (this.IsNew)
                {
                    LoadProperty(KidIDProperty, scm.Parameters["@KidID"].Value);
                }
            };
        }

        protected override void SaveChildren()
        {
            // No Children
        }

        protected override void SetupDeleteCommand(SqlCommand cm)
        {
            cm.Parameters.AddWithValue("@KidID", GetProperty(KidIDProperty));
        }

        #endregion

    }

}